### ISSUE TITLE
test is error 

### ISSUE THREAD

**Issue by gaoyuanzong** [pangzixiang/vertx-http-gateway#49]
run LocalDevTest log is error

15:13:09.404 [vert.x-virtual-thread-33] DEBUG io.github.pangzixiang.whatsit.vertx.http.gateway.connector.VertxHttpGatewayConnectorMainVerticle -- Failed to register to vertx http gateway [localhost:9090/register?serviceName=test-service&servicePort=50991&instance=453945642]! (error=WebSocket upgrade failure: 404)
15:13:09.404 [vert.x-virtual-thread-34] DEBUG io.github.pangzixiang.whatsit.vertx.http.gateway.connector.VertxHttpGatewayConnectorMainVerticle -- Failed to register to vertx http gateway [localhost:9090/register?serviceName=test-service&servicePort=50991&instance=1060919965]! (error=WebSocket upgrade failure: 404)

**Comment by pangzixiang** [comment]
Hi @gaoyuanzong , actually I just checked this Class and it did work on my side.
Did you change something before running?
Or you can ignore this Class and follow the README guide to start up your own testing gateway server and testing service.
